# -*- coding: utf-8 -*-
"""Varios_diseños_[0,1].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ePlhaDwhIZzIsXQVgrqwsYsaUkA66Ixx
"""

import pymc as pm
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from google.colab import drive
from matplotlib.backends.backend_pdf import PdfPages
from itertools import combinations
import warnings
from collections import defaultdict


# Silenciar warnings de glifos faltantes
warnings.filterwarnings("ignore", "Glyph .* missing from font")

# Montamos Google Drive
drive.mount('/content/drive')

# Ruta de tu CSV y del PDF de salida
filepath = "/content/drive/MyDrive/Mutualidad/Test AB/[001]/Análisis Mutualidad Test [001]  - 001.csv"
output_pdf = "/content/drive/MyDrive/Mutualidad/Test AB/[001]/Análisis Mutualidad Test [001]  - 001.pdf"

from google.colab import drive
drive.mount('/content/drive')

import os
from openai import OpenAI

# ⚠️ Asegúrate de poner tu clave real aquí
os.environ["OPENAI_API_KEY"] = "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"
client = OpenAI()

def interpretar_con_ia(resultados):
    """
    Usa ChatGPT para generar una interpretación ejecutiva
    de los resultados bayesianos A/B, recibiendo TODOS los datos estadísticos.
    """

    resumen_grupos = []
    comparativas = []

    # Extraemos toda la información disponible en el diccionario de resultados
    for k, v in resultados.items():

        # 1. INFORMACIÓN DE LOS GRUPOS (Incluyendo Acumulados)
        if isinstance(v, dict) and 'media' in v:
            # Recuperamos los acumulados que están en el nivel superior del diccionario
            visitas_acum = resultados.get(f"acum_visitas_{k}", "N/A")
            conv_acum = resultados.get(f"acum_clicks_{k}", "N/A")

            resumen_grupos.append(
                f"Grupo {k}: "
                f"Visitas Acumuladas={visitas_acum}, "
                f"Conversiones Acumuladas={conv_acum}, "
                f"Tasa Media={v['media']:.4f}, "
                f"IC95% (Tasa)=[{v['ci'][0]:.4f}, {v['ci'][1]:.4f}]"
            )

        # 2. INFORMACIÓN DE LAS COMPARATIVAS (Incluyendo los 3 Intervalos de Uplift)
        if "_vs_" in k and isinstance(v, dict):
            # Formateamos los 3 tipos de intervalos para que la IA tenga la foto completa del riesgo
            ic_centrado = f"[{v['ci_centered'][0]*100:.2f}%, {v['ci_centered'][1]*100:.2f}%]"
            ic_suelo = f"> {v['ci_right'][0]*100:.2f}%"  # Mínima mejora (Intervalo derecho)
            ic_techo = f"< {v['ci_left'][1]*100:.2f}%"   # Máximo riesgo (Intervalo izquierdo)

            comparativas.append(
                f"COMPARATIVA {k}: \n"
                f"   - Probabilidad de que el primero sea mejor: {v['prob_mejor']*100:.2f}%\n"
                f"   - Uplift Medio Estimado: {v['uplift_media']*100:.2f}%\n"
                f"   - Intervalo de Credibilidad (CENTRADO 95%): {ic_centrado} (USAR PARA REGLA DEL CERO)\n"
                f"   - Intervalo Unilateral (SUELO - Peor caso si gana): {ic_suelo}\n"
                f"   - Intervalo Unilateral (TECHO - Mejor caso si pierde): {ic_techo}"
            )

    # El prompt se mantiene con tus instrucciones, pero ahora recibe datos mucho más ricos
    prompt = f"""
Eres un experto Senior en Estadística Bayesiana y Experimentación (A/B Testing). Tu trabajo es interpretar los resultados de un experimento y dar una recomendación de negocio.

TUS INSTRUCCIONES CLAVE:

Contexto del Objetivo: Antes de decidir un ganador, contempla que el objetivo puede ser el de MAXIMIZAR la métrica (ej. ventas, CTR) o MINIMIZARLA (ej. tasa de rebote, bajas, errores). Ofrece las dos interpretaciones

Si Minimizar: Buscamos 'Probabilidad A > B' > 95%.

Si Maximizar: Buscamos 'Probabilidad B > A' > 95%.

LA REGLA DEL CERO (Crucial):

Analiza el Intervalo de Credibilidad (IC) del Uplift (El centrado me interesa menos que los otros).

Si el intervalo incluye el 0% (ej: de -5% a +5%): NO hay diferencia concluyente. El resultado es compatible con la hipótesis nula (efecto nulo). No puedes declarar ganador, sin importar la media.

Si el intervalo NO incluye el 0%: Existe una diferencia creíble.

Todo positivo (ej: +2% a +10%): Mejora confirmada.

Todo negativo (ej: -10% a -2%): Empeoramiento confirmado.

Gestión de Riesgo: Traduce el límite 'peor caso' (Suelo/Techo) del intervalo a lenguaje de negocio. (Ej: 'En el peor de los casos, la variante B no solo no mejora, sino que podría hacernos perder un 5%')."

Recomendación: ¿Detener el test o continuar?"

DATOS COMPLETOS DEL ÚLTIMO DÍA:
---------------------
{chr(10).join(resumen_grupos)}

COMPARATIVAS DETALLADAS:
{chr(10).join(comparativas)}
---------------------

Lenguaje claro, ejecutivo y sin fórmulas.
"""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "Eres un analista senior de CRO."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.2
    )

    return response.choices[0].message.content

sns.set(style="whitegrid")

class ConversionBayesMultiGrupo:
    def __init__(self, priors):
        self.priors = priors.copy()
        self.historial = []
        self.acumulados = {grupo: {'visitas': 0, 'conv': 0} for grupo in priors}

    def actualizar_con_datos(self, datos, dia=None, num_samples=100000):
        resultados = {'dia': dia or f"Día {len(self.historial)+1}"}
        muestras = {}
        grupos = list(datos.keys())
        tasas_conversion = {}

        for grupo in grupos:
            alpha0, beta0 = self.priors.get(grupo, (1, 1))
            visitas, conv = datos[grupo]
            alpha_post = alpha0 + conv
            beta_post = beta0 + visitas - conv

            muestras_array = np.random.beta(alpha_post, beta_post, num_samples).astype(np.float64)
            muestras[grupo] = muestras_array

            mean = alpha_post / (alpha_post + beta_post)
            std = np.sqrt((alpha_post * beta_post) / (((alpha_post + beta_post) ** 2) * (alpha_post + beta_post + 1)))
            ci = np.percentile(muestras_array, [2.5, 97.5])

            resultados[grupo] = {
                'media': mean,
                'std': std,
                'ci': ci,
                'muestras': muestras_array
            }

            tasa = conv / visitas if visitas > 0 else 0
            tasas_conversion[grupo] = tasa
            resultados[f"visitas_{grupo}"] = visitas
            resultados[f"conv_{grupo}"] = conv
            resultados[f"tasa_{grupo}"] = tasa

            self.priors[grupo] = (alpha_post, beta_post)
            if grupo not in self.acumulados:
                self.acumulados[grupo] = {'conv': 0, 'visitas': 0}
            self.acumulados[grupo]['conv'] += conv
            self.acumulados[grupo]['visitas'] += visitas

        if len(grupos) >= 2:
            a, b = grupos[0], grupos[1]
            total_a = self.acumulados[a]
            total_b = self.acumulados[b]
            tasa_a1 = total_a['conv'] / total_a['visitas'] if total_a['visitas'] > 0 else 0
            tasa_b1 = total_b['conv'] / total_b['visitas'] if total_b['visitas'] > 0 else 0
            uplift1 = (tasa_b1 - tasa_a1) / tasa_a1 if tasa_a1 > 0 else None
            resultados['uplift1'] = uplift1

        for g1, g2 in combinations(grupos, 2):
            for (a, b) in [(g1, g2), (g2, g1)]:
                tasa_a = muestras[a]
                tasa_b = muestras[b]
                uplift = (tasa_a - tasa_b) / tasa_b
                diff = tasa_a - tasa_b
                prob_mejor = np.mean(diff > 0)
                mean_uplift = np.mean(uplift)
                std_uplift = np.std(uplift)
                ci_uplift = np.percentile(uplift, [2.5, 97.5])

                resultados[f"{a}_vs_{b}"] = {
                    'uplift_media': mean_uplift,
                    'uplift_std': std_uplift,
                    'uplift_ci': ci_uplift,
                    'prob_mejor': prob_mejor,
                    'ganador': a if prob_mejor >= 0.95 else None,
                    'diff': diff,
                    'uplift1': resultados.get('uplift1')
                }

        self.historial.append(resultados)

    def mostrar_resultados_con_graficos(self, pdf: PdfPages = None):
        for paso in self.historial:
            dia = paso['dia']
            try:
                dia_num = int(dia.split()[1])
            except:
                dia_num = None

            lines = [f"🗓️  {dia}"]
            grupos = [g for g in paso if isinstance(paso[g], dict) and 'media' in paso[g]]
            for grupo in grupos:
                stats = paso[grupo]
                lines += [
                    f"Grupo {grupo}:",
                    f"  Media esperada: {stats['media']*100:.2f}%",
                    f"  Desviación estándar: {stats['std']*100:.2f}%",
                    f"  IC 95%: [{stats['ci'][0]*100:.2f}%, {stats['ci'][1]*100:.2f}%]"
                ]

            print("\n" + "\n".join(lines))
            if pdf is not None:
                fig_text = plt.figure(figsize=(8.27, 11.69))
                fig_text.clf()
                fig_text.text(0.01, 0.99, "\n".join(lines), va='top', family='monospace')
                pdf.savefig(fig_text)
                plt.close(fig_text)

            plt.figure(figsize=(10, 5))
            for grupo in grupos:
                muestras = paso[grupo]['muestras']
                sns.kdeplot(muestras, label=f"Grupo {grupo}", fill=True)
            plt.title(f"{dia} - Distribuciones posteriores (Beta)")
            plt.xlabel("Tasa de conversión")
            plt.legend()
            if pdf is not None:
                pdf.savefig()
            plt.show()
            plt.close()

            comparaciones = [k for k in paso if "_vs_" in k]
            for clave in comparaciones:
                stats = paso[clave]
                g1, g2 = clave.split("_vs_")
                comp_lines = [
                    f"\n📈 Uplift (relativo {g1} vs {g2}):",
                    f"  Media: {stats['uplift1']*100:.2f}%",
                    f"  Desviación estándar: {stats['uplift_std']*100:.2f}%",
                    f"  IC 95%: [{stats['uplift_ci'][0]*100:.2f}%, {stats['uplift_ci'][1]*100:.2f}%]",
                    f"\n📊 Probabilidad de que {g1} > {g2}: {stats['prob_mejor']*100:.2f}%"
                ]

                if stats['ganador']:
                    if dia_num is not None and dia_num < 6:
                        comp_lines += [
                            "\n⚠️ *Atención:*",
                            "Aún no has alcanzado el día 6.",
                            "Este resultado podría cambiar con más datos."
                        ]
                    else:
                        comp_lines += [
                            "\n🏆 Resultado final:",
                            f"  Ganador: {g1}",
                            f"  Decisión: Implementar {g1}",
                            f"  Razón: {g1} es mejor con {stats['prob_mejor']*100:.2f}% de probabilidad y {stats['uplift1']*100:.2f}% de mejora"
                        ]

                print("\n" + "\n".join(comp_lines))
                if pdf is not None:
                    fig_cmp = plt.figure(figsize=(8.27, 11.69))
                    fig_cmp.clf()
                    fig_cmp.text(0.01, 0.99, "\n".join(comp_lines), va='top', family='monospace')
                    pdf.savefig(fig_cmp)
                    plt.close(fig_cmp)

                plt.figure(figsize=(10, 4))
                sns.kdeplot(stats['diff'], label=f"Diferencia ({g1} - {g2})", fill=True)
                plt.axvline(0, color="black", linestyle="--")
                plt.title(f"{dia} - Diferencia de conversión: {g1} - {g2}")
                plt.xlabel("Diferencia")
                plt.legend()
                if pdf is not None:
                    pdf.savefig()
                plt.show()
                plt.close()

# === EJECUCIÓN ===

df = pd.read_csv(filepath)

# --- INSTRUCCIONES: EDUARDO
# Define tus conversiones y visitas esperadas aquí para cada grupo o variante.
# Cada entrada es: 'NOMBRE_GRUPO': (CONVERSIONES_ESPERADAS, VISITAS_ESPERADAS)
# Ejemplo: 'Control': (11, 91) significa 10 conversiones esperadas de 100 visitas.

datos_esperados_para_priors = {
    'A': (1, 1),
    'B': (1, 1),
    'C': (1, 1)
}
# -----------------------------------------------------------------

# Inicializa el diccionario para los priors de la distribución Beta
priors = {}

# Itera sobre los datos esperados para calcular los parámetros alfa y beta
for grupo, (conversiones, visitas) in datos_esperados_para_priors.items():
    # Validaciones básicas (opcional, pero recomendado)
    if not isinstance(conversiones, int) or not isinstance(visitas, int):
        print(f"Advertencia: Los valores para '{grupo}' deben ser enteros. Ignorando esta entrada.")
        continue
    if conversiones < 0 or visitas < 0:
        print(f"Advertencia: Conversiones y visitas para '{grupo}' no pueden ser negativas. Ignorando esta entrada.")
        continue
    if conversiones > visitas:
        print(f"Advertencia: Conversiones para '{grupo}' no pueden ser mayores que las visitas. Ignorando esta entrada.")
        continue

    # Cálculo de los parámetros alfa y beta para la distribución Beta
    # alfa (éxitos) = conversiones_esperadas + 1
    # beta (fracasos) = (visitas_esperadas - conversiones_esperadas) + 1
    alfa = conversiones + 1
    beta = (visitas - conversiones) + 1

    priors[grupo] = (alfa, beta)

# Imprime el resultado final
print("Priors para tus grupos (distribución Beta):")
print(priors)

# Si quieres acceder a un prior específico, por ejemplo, el de 'A':
# print(f"Prior para el grupo A: {priors.get('A')}")

modelo = ConversionBayesMultiGrupo(priors)

for _, row in df.iterrows():
    dia = f"Día {int(row['Día'])}"
    datos = {}
    for col in row.index:
        if col.startswith("Conversiones "):
            grupo = col.replace("Conversiones ", "")
            visitas_col = f"Visitas {grupo}"
            if visitas_col in row:
                conversiones = int(row[col])
                visitas = int(row[visitas_col])
                datos[grupo] = (visitas, conversiones)
    modelo.actualizar_con_datos(datos, dia=dia)

# Generamos el PDF y mostramos resultados
with PdfPages(output_pdf) as pdf:
    modelo.mostrar_resultados_con_graficos(pdf)

print(f"\n✅ Todo guardado en PDF: {output_pdf}")