# -*- coding: utf-8 -*-
"""Varios_diseños_[0,infinito].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XC0zpFwh4zZsnZunbIpLN8ED9ZGVQECu
"""

from google.colab import drive
drive.mount('/content/drive')

import pymc as pm
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from google.colab import drive
from matplotlib.backends.backend_pdf import PdfPages
from itertools import combinations
import warnings
from collections import defaultdict
from openai import OpenAI



warnings.filterwarnings("ignore", "Glyph .* missing from font")
# Montamos Google Drive
drive.mount('/content/drive')

# Ruta de tu CSV y del PDF de salida
filepath = "/content/WP17 - 6 Weeks - Objetivo principal CMBs FH.csv"
output_pdf = "/content/drive/MyDrive/Mutualidad/Test AB/[001]/Análisis Mutualidad Test [001]  - 001.pdf"

import os
from openai import OpenAI

# ⚠️ Asegúrate de poner tu clave real aquí
os.environ["OPENAI_API_KEY"] = "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"
client = OpenAI()

def interpretar_con_ia(resultados):
    """
    Usa ChatGPT para generar una interpretación ejecutiva
    de los resultados bayesianos A/B, recibiendo TODOS los datos estadísticos.
    """

    resumen_grupos = []
    comparativas = []

    # Extraemos toda la información disponible en el diccionario de resultados
    for k, v in resultados.items():

        # 1. INFORMACIÓN DE LOS GRUPOS (Incluyendo Acumulados)
        if isinstance(v, dict) and 'media' in v:
            # Recuperamos los acumulados que están en el nivel superior del diccionario
            visitas_acum = resultados.get(f"acum_visitas_{k}", "N/A")
            conv_acum = resultados.get(f"acum_clicks_{k}", "N/A")

            resumen_grupos.append(
                f"Grupo {k}: "
                f"Visitas Acumuladas={visitas_acum}, "
                f"Conversiones Acumuladas={conv_acum}, "
                f"Tasa Media={v['media']:.4f}, "
                f"IC95% (Tasa)=[{v['ci'][0]:.4f}, {v['ci'][1]:.4f}]"
            )

        # 2. INFORMACIÓN DE LAS COMPARATIVAS (Incluyendo los 3 Intervalos de Uplift)
        if "_vs_" in k and isinstance(v, dict):
            # Formateamos los 3 tipos de intervalos para que la IA tenga la foto completa del riesgo
            ic_centrado = f"[{v['ci_centered'][0]*100:.2f}%, {v['ci_centered'][1]*100:.2f}%]"
            ic_suelo = f"> {v['ci_right'][0]*100:.2f}%"  # Mínima mejora (Intervalo derecho)
            ic_techo = f"< {v['ci_left'][1]*100:.2f}%"   # Máximo riesgo (Intervalo izquierdo)

            comparativas.append(
                f"COMPARATIVA {k}: \n"
                f"   - Probabilidad de que el primero sea mejor: {v['prob_mejor']*100:.2f}%\n"
                f"   - Uplift Medio Estimado: {v['uplift_media']*100:.2f}%\n"
                f"   - Intervalo de Credibilidad (CENTRADO 95%): {ic_centrado} (USAR PARA REGLA DEL CERO)\n"
                f"   - Intervalo Unilateral (SUELO - Peor caso si gana): {ic_suelo}\n"
                f"   - Intervalo Unilateral (TECHO - Mejor caso si pierde): {ic_techo}"
            )

    # El prompt se mantiene con tus instrucciones, pero ahora recibe datos mucho más ricos
    prompt = f"""
Eres un experto Senior en Estadística Bayesiana y Experimentación (A/B Testing). Tu trabajo es interpretar los resultados de un experimento y dar una recomendación de negocio.

TUS INSTRUCCIONES CLAVE:

Contexto del Objetivo: Antes de decidir un ganador, contempla que el objetivo puede ser el de MAXIMIZAR la métrica (ej. ventas, CTR) o MINIMIZARLA (ej. tasa de rebote, bajas, errores). Ofrece las dos interpretaciones

Si Minimizar: Buscamos 'Probabilidad A > B' > 95%.

Si Maximizar: Buscamos 'Probabilidad B > A' > 95%.

LA REGLA DEL CERO (Crucial):

Analiza el Intervalo de Credibilidad (IC) del Uplift (El centrado me interesa menos que los otros) .

Si el intervalo incluye el 0% (ej: de -5% a +5%): NO hay diferencia concluyente. El resultado es compatible con la hipótesis nula (efecto nulo). No puedes declarar ganador, sin importar la media.

Si el intervalo NO incluye el 0%: Existe una diferencia creíble.

Todo positivo (ej: +2% a +10%): Mejora confirmada.

Todo negativo (ej: -10% a -2%): Empeoramiento confirmado.

Gestión de Riesgo: Traduce el límite 'peor caso' (Suelo/Techo) del intervalo a lenguaje de negocio. (Ej: 'En el peor de los casos, la variante B no solo no mejora, sino que podría hacernos perder un 5%')."

Recomendación: ¿Detener el test o continuar?"

DATOS COMPLETOS DEL ÚLTIMO DÍA:
---------------------
{chr(10).join(resumen_grupos)}

COMPARATIVAS DETALLADAS:
{chr(10).join(comparativas)}
---------------------

Lenguaje claro, ejecutivo y sin fórmulas.
"""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "Eres un analista de CRO."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.2
    )

    return response.choices[0].message.content

class ConversionBayesGamma:
    def __init__(self, priors):
        self.priors = priors.copy()
        self.historial = []
        self.acumulados = defaultdict(lambda: {'clicks': 0, 'visitas': 0})

    def actualizar_con_datos(self, datos, dia=None, num_samples=100000):
        resultados = {'dia': dia or f"Día {len(self.historial)+1}"}
        muestras = {}
        grupos = list(datos.keys())

        for grupo in grupos:
            alpha0, beta0 = self.priors.get(grupo, (1, 1))
            visitas, clicks = datos[grupo]

            # Cálculo Gamma (Rate)
            alpha_post = alpha0 + clicks
            beta_post = beta0 + visitas

            muestras_array = np.random.gamma(shape=alpha_post, scale=1/beta_post, size=num_samples)
            muestras[grupo] = muestras_array

            mean = np.mean(muestras_array)
            std = np.std(muestras_array)
            ci = np.percentile(muestras_array, [2.5, 97.5])

            self.acumulados[grupo]['clicks'] += clicks
            self.acumulados[grupo]['visitas'] += visitas
            self.priors[grupo] = (alpha_post, beta_post)

            resultados[f"acum_visitas_{grupo}"] = self.acumulados[grupo]['visitas']
            resultados[f"acum_clicks_{grupo}"] = self.acumulados[grupo]['clicks']

            resultados[grupo] = {
                'media': mean,
                'std': std,
                'ci': ci,
                'muestras': muestras_array
            }

        # Uplift
        for g1, g2 in combinations(grupos, 2):
            for (a, b) in [(g1, g2), (g2, g1)]:
                tasa_a = muestras[a]
                tasa_b = muestras[b]

                uplift = np.where(tasa_b != 0, (tasa_a - tasa_b) / tasa_b, 0)
                diff = tasa_a - tasa_b
                prob_mejor = np.mean(diff > 0)

                mean_uplift = np.mean(uplift)
                std_uplift = np.std(uplift)

                # Intervalos
                ci_centered = np.percentile(uplift, [2.5, 97.5])

                if mean_uplift > 0:
                    ci_unilateral = np.percentile(uplift, [5.0, 100.0])
                    tipo_ic = "Suelo (> 5%)"
                else:
                    ci_unilateral = np.percentile(uplift, [0.0, 95.0])
                    tipo_ic = "Techo (< 95%)"

                # Guardamos tambien derecha e izquierda para pintar si queremos
                ci_right = np.percentile(uplift, [5.0, 100.0])
                ci_left = np.percentile(uplift, [0.0, 95.0])

                resultados[f"{a}_vs_{b}"] = {
                    'uplift_media': mean_uplift,
                    'uplift_std': std_uplift,
                    'ci_centered': ci_centered,
                    'ci_right': ci_right,
                    'ci_left': ci_left,
                    'uplift_ci': ci_unilateral, # El que usamos para la IA
                    'tipo_ic': tipo_ic,
                    'prob_mejor': prob_mejor,
                    'ganador': a if prob_mejor >= 0.95 else None,
                    'diff': diff
                }

        self.historial.append(resultados)

    def mostrar_resultados_con_graficos(self, pdf: PdfPages = None):
        for paso in self.historial:
            dia = paso['dia']
            try: dia_num = int(dia.split()[1])
            except: dia_num = None

            lines = [f"🗓️  {dia}"]
            grupos = [g for g in paso if isinstance(paso[g], dict) and 'media' in paso[g]]
            for grupo in grupos:
                stats = paso[grupo]
                acum_v = paso.get(f"acum_visitas_{grupo}", 0)
                acum_c = paso.get(f"acum_clicks_{grupo}", 0)
                lines += [
                    f"Grupo {grupo}:",
                    f"  📊 Acumulado: {acum_v} visitas | {acum_c} conversiones",
                    f"  Media CTR: {stats['media']:.4f}",
                    f"  IC 95% (Centrado): [{stats['ci'][0]:.4f}, {stats['ci'][1]:.4f}]"
                ]

            print("\n" + "\n".join(lines))
            if pdf is not None:
                fig_text = plt.figure(figsize=(8.27, 11.69))
                fig_text.clf()
                fig_text.text(0.01, 0.99, "\n".join(lines), va='top', family='monospace')
                pdf.savefig(fig_text)
                plt.close(fig_text)

            # Gráfico de distribuciones posteriores
            plt.figure(figsize=(10, 5))
            ploteado = False
            for grupo in grupos:
                muestras = paso[grupo]['muestras']
                if len(muestras) > 0 and not np.allclose(muestras, muestras[0]):
                    sns.kdeplot(muestras, label=f"Grupo {grupo}", fill=True)
                    ploteado = True
            plt.title(f"{dia} - Distribuciones posteriores (Gamma)")
            plt.xlabel("CTR (Clicks por visita)")
            if ploteado: plt.legend()
            if pdf is not None: pdf.savefig()
            plt.show()
            plt.close()

            # Comparaciones
            comparaciones = [k for k in paso if "_vs_" in k]
            for clave in comparaciones:
                stats = paso[clave]
                g1, g2 = clave.split("_vs_")

                str_cent = f"[{stats['ci_centered'][0]*100:.2f}%, {stats['ci_centered'][1]*100:.2f}%]"
                str_right = f"> {stats['ci_right'][0]*100:.2f}%"
                str_left = f"< {stats['ci_left'][1]*100:.2f}%"

                comp_lines = [
                    f"\n📈 Uplift (relativo {g1} vs {g2}):",
                    f"  Media estimada: {stats['uplift_media']*100:.2f}%",
                    f"  ------------------------------------------------",
                    f"  1. IC Centrado:   {str_cent}",
                    f"  2. IC Derecha:    {str_right} (Suelo 95%)",
                    f"  3. IC Izquierda:  {str_left} (Techo 95%)",
                    f"  ------------------------------------------------",
                    f"  Probabilidad {g1} > {g2}: {stats['prob_mejor']*100:.2f}%"
                ]

                if stats['ganador']:
                    if dia_num is not None and dia_num < 6:
                        comp_lines += ["\n⚠️ *Atención:* Falta data (Día < 6)."]
                    else:
                        comp_lines += [f"\n🏆 Resultado final: Ganador {g1}"]

                print("\n" + "\n".join(comp_lines))
                if pdf is not None:
                    fig_cmp_text = plt.figure(figsize=(8.27, 11.69))
                    fig_cmp_text.clf()
                    fig_cmp_text.text(0.01, 0.99, "\n".join(comp_lines), va='top', family='monospace')
                    pdf.savefig(fig_cmp_text)
                    plt.close(fig_cmp_text)

                plt.figure(figsize=(10, 4))
                sns.histplot(stats['diff'], stat="density", element="step", color="gray", alpha=0.3, label="Histograma Simulado")
                sns.kdeplot(stats['diff'], label=f"Densidad ({g1} - {g2})", fill=True, color="green", alpha=0.5)
                plt.axvline(0, color="black", linestyle="--")
                plt.title(f"{dia} - Diferencia CTR: {g1} - {g2}")
                plt.xlabel("Diferencia absoluta")
                plt.legend()
                if pdf is not None: pdf.savefig()
                plt.show()
                plt.close()

# --------------------------------------------------------------------------
# EJECUCIÓN PRINCIPAL
# --------------------------------------------------------------------------

# Carga de datos
df = pd.read_csv(filepath)

# Priors
datos_esperados = {'A': (0, 0), 'B': (0, 0)}
priors_gamma = {}
for categoria, (conversiones, visitas) in datos_esperados.items():
    priors_gamma[categoria] = (conversiones + 1, visitas + 1)

# Modelo
modelo_gamma = ConversionBayesGamma(priors=priors_gamma)

# Procesamiento por día
for _, row in df.iterrows():
    dia = f"Día {int(row['Día'])}"
    datos = {}
    for col in row.index:
        if col.startswith("Conversiones "):
            grupo = col.replace("Conversiones ", "")
            visitas_col = f"Visitas {grupo}"
            if visitas_col in row:
                clicks = int(row[col])
                visitas = int(row[visitas_col])
                datos[grupo] = (visitas, clicks)
    modelo_gamma.actualizar_con_datos(datos, dia=dia)

# Generación PDF
output_dir = os.path.dirname(output_pdf)
os.makedirs(output_dir, exist_ok=True)

print(f"\n💾 Generando reporte y consultando a GPT-4o...")

with PdfPages(output_pdf) as pdf:
    # 1. Genera todos los gráficos y tablas en el PDF
    modelo_gamma.mostrar_resultados_con_graficos(pdf)

    # 2. LLAMADA A LA API DE OPENAI (Solo con los resultados del último día)
    try:
        if modelo_gamma.historial:
            ultimos_resultados = modelo_gamma.historial[-1]
            analisis_ia = interpretar_con_ia(ultimos_resultados)

            # Imprimimos en consola
            print("\n" + "="*50)
            print("🤖 ANÁLISIS AUTOMÁTICO (GPT-4o):")
            print("="*50)
            print(analisis_ia)
            print("="*50)

            # Escribimos en una nueva página del PDF
            fig_ia = plt.figure(figsize=(8.27, 11.69))
            fig_ia.clf()

            # Título
            plt.text(0.5, 0.95, "ANÁLISIS EJECUTIVO IA (GPT-4o)",
                     ha='center', va='center', fontsize=16, weight='bold')

            # Cuerpo del texto (ajustamos saltos de línea para que no se corte)
            import textwrap
            wrapped_text = "\n".join(textwrap.wrap(analisis_ia, width=80))

            plt.text(0.05, 0.90, wrapped_text,
                     ha='left', va='top', fontsize=11, family='monospace')

            plt.axis('off')
            pdf.savefig(fig_ia)
            plt.close(fig_ia)

    except Exception as e:
        print(f"⚠️ No se pudo generar el análisis de IA: {e}")

print(f"\n✅ Todo guardado en PDF: {output_pdf}")