# -*- coding: utf-8 -*-
"""Varios_diseños_sessionid_[0,1].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkTEkGALayNtnoejv4IR1jPlDVKX057E
"""

import pymc as pm
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from google.colab import drive
from matplotlib.backends.backend_pdf import PdfPages
from itertools import combinations
import warnings
from collections import defaultdict


# Silenciar warnings de glifos faltantes
warnings.filterwarnings("ignore", "Glyph .* missing from font")

# Montamos Google Drive
drive.mount('/content/drive')

# Ruta de tu CSV y del PDF de salida
filepath = "/content/drive/MyDrive/CRO/Pruebas/Prueba 2 - Sheet1.csv"
output_pdf = "/content/drive/MyDrive/CRO/Pruebas/Prueba 2 - Sheet1.pdf"

from google.colab import drive
drive.mount('/content/drive')

import os
from openai import OpenAI

# ⚠️ Asegúrate de poner tu clave real aquí
os.environ["OPENAI_API_KEY"] = "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"
client = OpenAI()

def interpretar_con_ia(resultados):
    """
    Usa ChatGPT para generar una interpretación ejecutiva
    de los resultados bayesianos A/B, recibiendo TODOS los datos estadísticos.
    """

    resumen_grupos = []
    comparativas = []

    # Extraemos toda la información disponible en el diccionario de resultados
    for k, v in resultados.items():

        # 1. INFORMACIÓN DE LOS GRUPOS (Incluyendo Acumulados)
        if isinstance(v, dict) and 'media' in v:
            # Recuperamos los acumulados que están en el nivel superior del diccionario
            visitas_acum = resultados.get(f"acum_visitas_{k}", "N/A")
            conv_acum = resultados.get(f"acum_clicks_{k}", "N/A")

            resumen_grupos.append(
                f"Grupo {k}: "
                f"Visitas Acumuladas={visitas_acum}, "
                f"Conversiones Acumuladas={conv_acum}, "
                f"Tasa Media={v['media']:.4f}, "
                f"IC95% (Tasa)=[{v['ci'][0]:.4f}, {v['ci'][1]:.4f}]"
            )

        # 2. INFORMACIÓN DE LAS COMPARATIVAS (Incluyendo los 3 Intervalos de Uplift)
        if "_vs_" in k and isinstance(v, dict):
            # Formateamos los 3 tipos de intervalos para que la IA tenga la foto completa del riesgo
            ic_centrado = f"[{v['ci_centered'][0]*100:.2f}%, {v['ci_centered'][1]*100:.2f}%]"
            ic_suelo = f"> {v['ci_right'][0]*100:.2f}%"  # Mínima mejora (Intervalo derecho)
            ic_techo = f"< {v['ci_left'][1]*100:.2f}%"   # Máximo riesgo (Intervalo izquierdo)

            comparativas.append(
                f"COMPARATIVA {k}: \n"
                f"   - Probabilidad de que el primero sea mejor: {v['prob_mejor']*100:.2f}%\n"
                f"   - Uplift Medio Estimado: {v['uplift_media']*100:.2f}%\n"
                f"   - Intervalo de Credibilidad (CENTRADO 95%): {ic_centrado} (USAR PARA REGLA DEL CERO)\n"
                f"   - Intervalo Unilateral (SUELO - Peor caso si gana): {ic_suelo}\n"
                f"   - Intervalo Unilateral (TECHO - Mejor caso si pierde): {ic_techo}"
            )

    # El prompt se mantiene con tus instrucciones, pero ahora recibe datos mucho más ricos
    prompt = f"""
Eres un experto Senior en Estadística Bayesiana y Experimentación (A/B Testing). Tu trabajo es interpretar los resultados de un experimento y dar una recomendación de negocio.

TUS INSTRUCCIONES CLAVE:

Contexto del Objetivo: Antes de decidir un ganador, contempla que el objetivo puede ser el de MAXIMIZAR la métrica (ej. ventas, CTR) o MINIMIZARLA (ej. tasa de rebote, bajas, errores). Ofrece las dos interpretaciones

Si Minimizar: Buscamos 'Probabilidad A > B' > 95%.

Si Maximizar: Buscamos 'Probabilidad B > A' > 95%.

LA REGLA DEL CERO (Crucial):

Analiza el Intervalo de Credibilidad (IC) del Uplift (El centrado me interesa menos que los otros).

Si el intervalo incluye el 0% (ej: de -5% a +5%): NO hay diferencia concluyente. El resultado es compatible con la hipótesis nula (efecto nulo). No puedes declarar ganador, sin importar la media.

Si el intervalo NO incluye el 0%: Existe una diferencia creíble.

Todo positivo (ej: +2% a +10%): Mejora confirmada.

Todo negativo (ej: -10% a -2%): Empeoramiento confirmado.

Gestión de Riesgo: Traduce el límite 'peor caso' (Suelo/Techo) del intervalo a lenguaje de negocio. (Ej: 'En el peor de los casos, la variante B no solo no mejora, sino que podría hacernos perder un 5%')."

Recomendación: ¿Detener el test o continuar?"

DATOS COMPLETOS DEL ÚLTIMO DÍA:
---------------------
{chr(10).join(resumen_grupos)}

COMPARATIVAS DETALLADAS:
{chr(10).join(comparativas)}
---------------------

Lenguaje claro, ejecutivo y sin fórmulas.
"""

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "Eres un analista senior de CRO."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.2
    )

    return response.choices[0].message.content

sns.set(style="whitegrid")

class ConversionBayesBeta:
    def __init__(self, priors):
        self.priors = priors.copy()
        self.historial = []
        self.acumulados = defaultdict(lambda: {'clicks': 0, 'visitas': 0})

    def actualizar_con_datos(self, datos, raw_data=None, dia=None, num_samples=100000):
        # raw_data: DataFrame con las filas del día para el histograma
        resultados = {
            'dia': dia or f"Día {len(self.historial)+1}",
            'raw_data': raw_data
        }
        muestras = {}
        grupos = list(datos.keys())

        # --- 1. Muestreo Bayesiano (BETA) ---
        for grupo in grupos:
            alpha0, beta0 = self.priors.get(grupo, (1, 1))

            # Datos del día (Totales calculados previamente)
            visitas_dia, clicks_dia = datos[grupo]

            # Actualizamos Acumulados
            self.acumulados[grupo]['clicks'] += clicks_dia
            self.acumulados[grupo]['visitas'] += visitas_dia

            total_visitas = self.acumulados[grupo]['visitas']
            total_clicks = self.acumulados[grupo]['clicks']
            total_fracasos = total_visitas - total_clicks

            # Beta Update: Alpha += Éxitos, Beta += Fracasos
            alpha_post = alpha0 + total_clicks
            beta_post = beta0 + total_fracasos

            # Muestreo Beta
            muestras_array = np.random.beta(a=alpha_post, b=beta_post, size=num_samples)
            muestras[grupo] = muestras_array

            mean = np.mean(muestras_array)
            std = np.std(muestras_array)
            ci = np.percentile(muestras_array, [2.5, 97.5])

            resultados[f"acum_visitas_{grupo}"] = total_visitas
            resultados[f"acum_clicks_{grupo}"] = total_clicks

            resultados[grupo] = {
                'media': mean,
                'std': std,
                'ci': ci,
                'muestras': muestras_array
            }

        # --- 2. Comparaciones ---
        for g1, g2 in combinations(grupos, 2):
            for (a, b) in [(g1, g2), (g2, g1)]:
                tasa_a = muestras[a]
                tasa_b = muestras[b]

                # Uplift relativo
                uplift_samples = np.where(tasa_b != 0, (tasa_a - tasa_b) / tasa_b, 0)
                diff_samples = tasa_a - tasa_b

                prob_mejor = np.mean(diff_samples > 0)
                mean_uplift = np.mean(uplift_samples)
                std_uplift = np.std(uplift_samples)

                # 3 Intervalos
                ci_centered = np.percentile(uplift_samples, [2.5, 97.5])
                ci_right = np.percentile(uplift_samples, [5.0, 100.0])
                ci_left = np.percentile(uplift_samples, [0.0, 95.0])

                resultados[f"{a}_vs_{b}"] = {
                    'uplift_media': mean_uplift,
                    'uplift_std': std_uplift,
                    'ci_centered': ci_centered,
                    'ci_right': ci_right,
                    'ci_left': ci_left,
                    'prob_mejor': prob_mejor,
                    'ganador': a if prob_mejor >= 0.95 else None,
                    'diff': diff_samples
                }

        self.historial.append(resultados)

    def mostrar_resultados_con_graficos(self, pdf: PdfPages = None):
        for paso in self.historial:
            dia = paso['dia']
            raw_data = paso.get('raw_data')

            lines = [f"🗓️  {dia}"]
            grupos = [g for g in paso if isinstance(paso[g], dict) and 'media' in paso[g]]

            for grupo in grupos:
                stats = paso[grupo]
                total_v = paso.get(f"acum_visitas_{grupo}", 0)
                total_c = paso.get(f"acum_clicks_{grupo}", 0)
                lines += [
                    f"Grupo {grupo}:",
                    f"  📊 Acumulado: {total_v} visitas | {total_c} conversiones",
                    f"  Media CR: {stats['media']:.2%}",
                    f"  IC 95% (Centrado): [{stats['ci'][0]:.2%}, {stats['ci'][1]:.2%}]"
                ]

            print("\n" + "="*40 + "\n" + "\n".join(lines))
            if pdf is not None:
                fig_text = plt.figure(figsize=(8.27, 11.69))
                fig_text.clf()
                fig_text.text(0.05, 0.95, "\n".join(lines), va='top', family='monospace', fontsize=10)
                pdf.savefig(fig_text)
                plt.close(fig_text)

            # 1. HISTOGRAMA DE DATOS CRUDOS (Raw Data)
            # Solo si tenemos datos detallados
            if raw_data is not None and not raw_data.empty:
                plt.figure(figsize=(10, 5))
                # dropna() es vital aquí para ignorar los huecos vacíos (no visitas)
                if 'Conversiones A' in raw_data.columns:
                    sns.histplot(raw_data['Conversiones A'].dropna(), color="blue", label="Grupo A", kde=False, element="step", alpha=0.4, discrete=True)
                if 'Conversiones B' in raw_data.columns:
                    sns.histplot(raw_data['Conversiones B'].dropna(), color="orange", label="Grupo B", kde=False, element="step", alpha=0.4, discrete=True)

                plt.title(f"{dia} - Distribución Real (0=No conv, 1=Conv)")
                plt.xlabel("Valor de Conversión")
                plt.ylabel("Frecuencia (Usuarios)")
                plt.legend()
                if pdf is not None: pdf.savefig()
                plt.show()
                plt.close()

            # 2. DISTRIBUCIONES POSTERIORES (BETA)
            plt.figure(figsize=(10, 5))
            ploteado = False
            for grupo in grupos:
                muestras = paso[grupo]['muestras']
                if len(muestras) > 0:
                    sns.kdeplot(muestras, label=f"Grupo {grupo}", fill=True)
                    ploteado = True
            plt.title(f"{dia} - Incertidumbre Tasa Conversión (Modelo Beta)")
            plt.xlabel("Tasa de Conversión Estimada")
            if ploteado: plt.legend()
            if pdf is not None: pdf.savefig()
            plt.show()
            plt.close()

            # 3. COMPARACIONES
            comparaciones = [k for k in paso if "_vs_" in k]
            for clave in comparaciones:
                stats = paso[clave]
                g1, g2 = clave.split("_vs_")

                str_cent = f"[{stats['ci_centered'][0]*100:.2f}%, {stats['ci_centered'][1]*100:.2f}%]"
                str_right = f"> {stats['ci_right'][0]*100:.2f}%"
                str_left = f"< {stats['ci_left'][1]*100:.2f}%"

                comp_lines = [
                    f"\n📈 Uplift (relativo {g1} vs {g2}):",
                    f"  Media estimada: {stats['uplift_media']*100:.2f}%",
                    f"  ------------------------------------------------",
                    f"  1. IC Centrado:   {str_cent}",
                    f"  2. IC Suelo:      {str_right} (Mínimo asegurado 95%)",
                    f"  3. IC Techo:      {str_left} (Máximo riesgo 95%)",
                    f"  ------------------------------------------------",
                    f"  Probabilidad {g1} > {g2}: {stats['prob_mejor']*100:.2f}%"
                ]
                if stats['ganador']:
                    comp_lines += [f"\n🏆 Ganador Probable: {stats['ganador']}"]

                print("\n".join(comp_lines))

                if pdf is not None:
                    fig_cmp_text = plt.figure(figsize=(8.27, 4))
                    fig_cmp_text.clf()
                    fig_cmp_text.text(0.05, 0.90, "\n".join(comp_lines), va='top', family='monospace', fontsize=10)
                    pdf.savefig(fig_cmp_text)
                    plt.close(fig_cmp_text)

                # 4. GRÁFICO DIFERENCIA
                plt.figure(figsize=(10, 5))
                sns.histplot(stats['diff'], stat="density", element="step", color="gray", alpha=0.3, label="Histograma")
                sns.kdeplot(stats['diff'], fill=True, color="green", alpha=0.4, label="Densidad")
                plt.axvline(0, color="red", linestyle="--", label="Ref (0)")
                plt.title(f"{dia} - Diferencia Absoluta ({g1} - {g2})")
                plt.xlabel("Diferencia en Tasa de Conversión")
                plt.legend()

                if pdf is not None: pdf.savefig()
                plt.show()
                plt.close()

# --------------------------------------------------------------------------
# 5. CARGA Y PROCESAMIENTO
# --------------------------------------------------------------------------

try:
    df = pd.read_csv(filepath)
    print("✅ CSV cargado.")
except Exception as e:
    print(f"❌ Error CSV: {e}")
    raise

# Priors Uniformes
datos_esperados = {'A': (0, 0), 'B': (0, 0)}
priors = {k: (1, 1) for k in datos_esperados}

modelo_beta = ConversionBayesBeta(priors=priors)

dias_unicos = sorted(df['Día'].unique())
print(f"🔄 Procesando {len(dias_unicos)} días de test...")

for dia_val in dias_unicos:
    # Filtramos el DataFrame solo para este día (Raw Data)
    df_dia = df[df['Día'] == dia_val].copy()

    # --- PROCESAMIENTO DE OBSERVACIONES ---
    # .count() ignora NaNs -> Calcula Visitas Reales
    # .sum() suma 1s -> Calcula Conversiones

    visitas_a = df_dia['Conversiones A'].count()
    visitas_b = df_dia['Conversiones B'].count()

    conv_a = df_dia['Conversiones A'].sum()
    conv_b = df_dia['Conversiones B'].sum()

    datos_agregados = {
        'A': (visitas_a, conv_a),
        'B': (visitas_b, conv_b)
    }

    # Pasamos AMBOS: los totales calculados Y los datos crudos para el histograma
    modelo_beta.actualizar_con_datos(
        datos=datos_agregados,
        raw_data=df_dia,
        dia=f"Día {int(dia_val)}"
    )

# --------------------------------------------------------------------------
# 6. GENERACIÓN
# --------------------------------------------------------------------------
output_dir = os.path.dirname(output_pdf)
if output_dir:
    os.makedirs(output_dir, exist_ok=True)

print(f"\n💾 Generando reporte...")

with PdfPages(output_pdf) as pdf:
    modelo_beta.mostrar_resultados_con_graficos(pdf)

    if modelo_beta.historial:
        print("🤖 Consultando IA...")
        analisis = interpretar_con_ia(modelo_beta.historial[-1])
        print("="*50 + f"\n{analisis}\n" + "="*50)



print(f"\n✅ Hecho: {output_pdf}")